# Generated by Django 4.2.2 on 2023-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('food_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('img', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
