# Generated by Django 4.2.2 on 2023-07-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0003_alter_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
