# Generated by Django 4.2.2 on 2023-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0005_alter_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
