# Generated by Django 4.2.3 on 2023-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0007_restaurant_restaurant_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.CharField(max_length=50)),
                ('Apswd', models.CharField(max_length=35)),
            ],
        ),
    ]
